#!/usr/bin/make

all: 
	$(MAKE) -C actor_factory 
	$(MAKE) -C xml
	$(MAKE) -C resource 

install:
	$(MAKE) -C actor_factory install
	$(MAKE) -C xml install
	$(MAKE) -C resource install

clean:
	$(MAKE) -C actor_factory clean
	$(MAKE) -C xml clean
	$(MAKE) -C resource clean

uninstall:
	$(MAKE) -C actor_factory uninstall
	$(MAKE) -C xml uninstall
	$(MAKE) -C resource uninstall

