#!/usr/bin/make

all: 
	$(MAKE) -C actor_factory 
	$(MAKE) -C xml

install:
	$(MAKE) -C actor_factory install
	$(MAKE) -C xml install

clean:
	$(MAKE) -C actor_factory clean
	$(MAKE) -C xml clean

uninstall:
	$(MAKE) -C actor_factory uninstall
	$(MAKE) -C xml uninstall
